#!/usr/bin/env bash

export DOCKER_RUN="docker-compose exec -T php"

function run { # run [NAME] [FUNCTION]
  echo "### $1"
  eval ${DOCKER_RUN} $2
  quit_when_fail
}

function run_files { # run_files [NAME] [EXTENSION] [FUNCTION]
  echo "### $1"
  git status --porcelain | grep -e "^[AM]\(.*\).${2}$" | cut -c 3- | while read file; do
    echo "  > "$file
    eval ${DOCKER_RUN} $3 ${file}
    git add $file
  done
}

function quit_when_fail { # quit_when_fail
  if [ $? -ne 0 ]; then
    echo " > Task failed, fix all things before commit!"
    exit 1
  fi
}

run_files PHP-CS-Fixer php "vendor/bin/php-cs-fixer fix"
run PHP_CodeSniffer "vendor/bin/phpcs -p"
run VarDump_Check "vendor/bin/var-dump-check --symfony src"
run Lint_YAML_config "bin/console lint:yaml config"
run Lint_YAML_translations "bin/console lint:yaml translations"
run Lint_TWIG_templates "bin/console lint:twig templates"
